global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:3000"]
    metrics_path: "/metrics"

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:3001"]
    metrics_path: "/metrics"

  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:3002"]
    metrics_path: "/metrics"

  - job_name: "core-service"
    static_configs:
      - targets: ["core-service:3003"]
    metrics_path: "/metrics"

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:3004"]
    metrics_path: "/metrics"

  - job_name: "audit-service"
    static_configs:
      - targets: ["audit-service:3005"]
    metrics_path: "/metrics"

  - job_name: "feature-flag-service"
    static_configs:
      - targets: ["feature-flag-service:3006"]
    metrics_path: "/metrics"
